apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravelapp1
  labels:
    app: laravelapp1
spec:
  selector:
    matchLabels:
      app: laravelapp1
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: laravelapp1
    spec:
      containers:
        - image: nasibmohammad/laravelapp01
          imagePullPolicy: Always
          name: laravelapp1
          ports:
            - containerPort: 80
