pipeline {

  environment {
    dockerimagename = "nasibmohammad/laravelapp01"
    dockerImage = ""
  }

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git branch: 'main', credentialsId: 'jenkins-user-github', url: 'https://github.com/nasib-mohammad-cs/projectChallange.git'
      }
    }
    

    stage('Build image for app1') {
        steps {
            dir(path: '/var/jenkins_home/workspace/taskOne/Task1/app1/SRC') {
                script {
                    //sh 'ls -la'
                dockerImage = docker.build dockerimagename
                
        }
        }

      }
    }

    stage('Pushing Image') {
      environment {
               registryCredential = 'dockerhublogin'
           }
      steps{
        script {
          docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
            dockerImage.push("latest")
          }
        }
      }
    }

    stage('Deploying App to Kubernetes') {
      steps {
          dir(path: '/var/jenkins_home/workspace/taskOne/Task1/app1/deploy') {
        script {
          kubernetesDeploy(configs: "deploymentservice.yml", kubeconfigId: "kubernetes")
        }
      }
      }
    }

  }

}
